version: "3.7"
services:
  app:
    build:
      args:
        user: admin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: question_paper_generator
    container_name: question_paper_generator-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - question_paper_generator

  db:
    image: mysql:8.0
    container_name: question_paper_generator-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: question-paper-generator
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: password
      MYSQL_USER: aravind
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports: 
    - 3306:3306
    networks:
      - question_paper_generator

  nginx:
    image: nginx:alpine
    container_name: question_paper_generator-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - question_paper_generator

networks:
  question_paper_generator:
    driver: bridge